"""
Centralized Comparison Networks — Layer 1
==========================================
Generates synthetic networks representing centralized architectures
to compare against biological (decentralized) networks.

Networks:
    1. Star graph — pure centralization (one hub controls everything)
    2. Erdos-Renyi random graph — no structure (null model)
    3. Regular lattice — uniform, rigid, no hubs
    4. Hub-and-spoke — hub nodes with radiating spokes (airline model)

Each is sized to match the biological network for fair comparison.

The thesis: biological networks will show fundamentally different
topology from all of these — scale-free degree distribution, higher
clustering, and dramatically better robustness than centralized forms.
"""

from __future__ import annotations
import networkx as nx
import numpy as np


def build_comparison_networks(
    n_nodes: int = 500,
    n_edges: int = 2000,
) -> dict[str, nx.Graph]:
    """
    Build a set of reference networks for comparison with biological networks.

    All networks are scaled to approximately the same number of nodes and edges
    as the biological network being compared.

    Returns dict with keys: 'star', 'random', 'lattice', 'hub_spoke'
    """
    networks = {}

    # --- 1. Star graph: pure centralization ---
    # One node connected to all others. Maximum centralization.
    # The dictator model: remove the hub, everything disconnects.
    G_star = nx.star_graph(n_nodes - 1)
    networks["Star (centralized)"] = G_star

    # --- 2. Erdos-Renyi random graph: null model ---
    # Each edge exists with equal probability. No structure.
    # This is the "noise" baseline — if biology looks like this,
    # there's no special organization.
    p = (2 * n_edges) / (n_nodes * (n_nodes - 1)) if n_nodes > 1 else 0
    p = min(p, 1.0)
    G_random = nx.erdos_renyi_graph(n_nodes, p, seed=42)
    networks["Random (Erdos-Renyi)"] = G_random

    # --- 3. Regular lattice: rigid uniformity ---
    # Every node has the same number of connections.
    # Represents engineered, top-down, uniform infrastructure.
    k = max(2, int(2 * n_edges / n_nodes))  # degree per node
    if k % 2 == 1:
        k -= 1  # watts_strogatz requires even k
    k = max(2, min(k, n_nodes - 1))
    G_lattice = nx.watts_strogatz_graph(n_nodes, k, 0, seed=42)  # p=0 = pure lattice
    networks["Lattice (uniform)"] = G_lattice

    # --- 4. Hub-and-spoke: controlled hierarchy ---
    # A small number of hub nodes, each connected to a cluster of spokes.
    # Models airline networks, corporate hierarchies, colonial empires.
    n_hubs = max(3, n_nodes // 50)
    spokes_per_hub = (n_nodes - n_hubs) // n_hubs
    G_hs = nx.Graph()

    hub_nodes = [f"hub_{i}" for i in range(n_hubs)]
    G_hs.add_nodes_from(hub_nodes)

    # Connect hubs to each other (fully connected core)
    for i in range(n_hubs):
        for j in range(i + 1, n_hubs):
            G_hs.add_edge(hub_nodes[i], hub_nodes[j])

    # Add spoke nodes around each hub
    spoke_id = 0
    for hub in hub_nodes:
        for _ in range(spokes_per_hub):
            spoke = f"spoke_{spoke_id}"
            G_hs.add_node(spoke)
            G_hs.add_edge(hub, spoke)
            spoke_id += 1

    # Fill remaining nodes
    while G_hs.number_of_nodes() < n_nodes:
        spoke = f"spoke_{spoke_id}"
        hub = hub_nodes[spoke_id % n_hubs]
        G_hs.add_node(spoke)
        G_hs.add_edge(hub, spoke)
        spoke_id += 1

    networks["Hub-and-spoke"] = G_hs

    # --- 5. Barabasi-Albert scale-free (for reference) ---
    # This IS scale-free but generated by preferential attachment.
    # Useful to show that biology matches this model.
    m = max(1, n_edges // n_nodes)
    G_ba = nx.barabasi_albert_graph(n_nodes, m, seed=42)
    networks["Scale-free (BA model)"] = G_ba

    # Report
    print("[comparison] Built reference networks:")
    for name, G in networks.items():
        print(f"  {name}: {G.number_of_nodes()} nodes, {G.number_of_edges()} edges")

    return networks


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    print("Building comparison networks (n=500, m=2000)...")
    nets = build_comparison_networks(500, 2000)

    for name, G in nets.items():
        degrees = [d for _, d in G.degree()]
        print(f"\n{name}:")
        print(f"  Nodes: {G.number_of_nodes()}, Edges: {G.number_of_edges()}")
        print(f"  Mean degree: {np.mean(degrees):.1f}")
        print(f"  Max degree: {max(degrees)}")
        print(f"  Components: {nx.number_connected_components(G)}")
